function panzoom
% создание окна приложения
figure('Resize', 'off', 'Menubar', 'none', ...
    'Name', 'panzoom', 'NumberTitle', 'off')
% создание осей приложения
axes('Position', [0.1 0.1 0.6 0.8])
% вывод графика
x = linspace(0.01,6,100000);
y = sin(1./x);
plot(x,y)
% создание панели переключателей
hbtngr = uibuttongroup('Position', [0.725 0.1 0.25 0.35],...
    'Title', 'Pan&Zoom','FontSize', 10, ...
    'SelectionChangeFcn',  @btnGroupChange);
% создание шести переключателей
uicontrol(hbtngr, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.8 0.8 0.1],...
    'String', 'pan x and y', 'Tag', 'rbtnPanXY',...
    'FontSize', 10)
uicontrol(hbtngr, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.7 0.8 0.1],...
    'String', 'pan x only', 'Tag', 'rbtnPanX',...
    'FontSize', 10)
uicontrol(hbtngr, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.6 0.8 0.1],...
    'String', 'pan y only', 'Tag', 'rbtnPanY',...
    'FontSize', 10)
rbtnZoom =  uicontrol(hbtngr, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.4 0.8 0.1],...
    'String', 'zoom x and y', 'Tag', 'rbtnZoomXY', ...
    'FontSize', 10);
uicontrol(hbtngr, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.3 0.8 0.1],...
    'String', 'zoom x only', 'Tag', 'rbtnZoomX',...
    'FontSize', 10)
uicontrol(hbtngr, 'Style', 'radiobutton', ...
    'Units', 'normalized', 'Position', [0.05 0.2 0.8 0.1],...
    'String', 'zoom y only', 'Tag', 'rbtnZoomY',...
    'FontSize', 10)
% включение переключателя 'zoom x and y'
set(hbtngr, 'SelectedObject', rbtnZoom)
% включение режима увеличения
zoom on

function btnGroupChange(src, evt)
% функция обработки события SelectionChangeFcn панели

% получение структуры указателей на объекты приложения
handles = guihandles(src);
% проверка включенного переключателя
if isequal(get(handles.rbtnPanXY, 'Value'), 1)
    pan on
elseif isequal(get(handles.rbtnPanX, 'Value'), 1)
    pan xon
elseif isequal(get(handles.rbtnPanY, 'Value'), 1)
    pan yon
elseif isequal(get(handles.rbtnZoomXY, 'Value'), 1)
    zoom on
elseif isequal(get(handles.rbtnZoomX, 'Value'), 1)
    zoom xon
else 
    zoom yon
end