/*
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: BASIC, 1.0 ---
 *
 *   This file is a wrapper S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand, 
 *   you must change it only in the area defined as:  
 *
 *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
 *            Your Changes go here
 *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
 *
 *   For better compatibility with the Real-Time Workshop, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Real-Time Workshop User's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *   Created: Sun Mar 30 13:07:10 2003
 */
/*
 * Include Files
 *
 */
#include "tmwtypes.h"
/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>

//=========================NEW CODE==================================
 double  A00, A01, A10, B00, B11, C00, C11;
//=========================NEW CODE==================================

/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
//extern double func(double a);

/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */
/*
 * Output functions
 *
 */
void DPT_Sfunc_1_C_Outputs_wrapper(const real_T *u,
                             real_T       *y,
                             const real_T *xC, 
                             const real_T  *param0, const int_T  p_width0, const real_T  *param1, const int_T  p_width1, const real_T  *param2, const int_T  p_width2, const real_T  *param3, const int_T  p_width3, const real_T  *param4, const int_T  p_width4,  const real_T *param5, const int_T p_width5)
{
  /* This Outputs function allows for 1 input and 1 output
   * signal of any width, any number of discrete states and 
   * parameters, all of type real_T.  
   *
   * If you need the FULL POWER of the S-function interface, 
   * familiarize yourself with the full template file at:
   * 
   *     matlabroot/simulink/src/sfuntmpl_doc.c
   *
   * and the "Writing S-functions" manual in the documentation.
   */
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */


//=========================OLD CODE==================================
/* double Cm = param3[0], Fi = param5[0];
 double C00=Cm*Fi, C11= 1; */
//=========================OLD CODE==================================
 
 y[0] = C00*xC[0]; 
 y[1] = C11*xC[1];

/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
 * Updates function
 *
 */
void DPT_Sfunc_1_C_Update_wrapper(const real_T *u,
                             const real_T *y, 
                             const real_T  *param0, const int_T  p_width0,const real_T  *param1, const int_T  p_width1,const real_T  *param2, const int_T  p_width2,const real_T  *param3, const int_T  p_width3,const real_T  *param4, const int_T  p_width4, const real_T  *param5, const int_T p_width5)
{
/* %%%-SFUNWIZ_wrapper_Update_Changes_BEGIN --- EDIT HERE TO _END */
/*
 * Code example
 *   xD[0] = u[0];
 */  
 
 
/* %%%-SFUNWIZ_wrapper_Update_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
 *  Derivatives function
 *
 */
void DPT_Sfunc_1_C_Derivatives_wrapper(const real_T *u,
                             const real_T *y, real_T *dx,
                             real_T      *xC, 
                             const real_T  *param0, const int_T  p_width0,const real_T  *param1, const int_T  p_width1,const real_T  *param2, const int_T  p_width2,const real_T  *param3, const int_T  p_width3,const real_T  *param4, const int_T  p_width4, const real_T  *param5, const int_T  p_width5)
{
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_BEGIN --- EDIT HERE TO _END */

//=========================OLD CODE==================================
/* double L = param0[0],  R = param1[0],  J =param2[0];
 double Cm = param3[0], Cw = param4[0], Fi=param5[0];

 double A00 = -R/L ,    A01 = -Cw*Fi/L , B00 = 1/L;
 double A10 = Cm*Fi/J , B11 = -1/J;  */
//=========================OLD CODE==================================

  dx[0] = A00*xC[0]+A01*xC[1]+B00*u[0];
  dx[1] = A10*xC[0]+B11*u[1];
 
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_END --- EDIT HERE TO _BEGIN */
}


